name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version: [5.1, 5.2, 5.3, 5.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Lua
      uses: leafo/gh-actions-lua@master
      with:
        lua-version: ${{ matrix.lua-version }}

    - name: Set up Luarocks
      uses: leafo/gh-actions-luarocks@master

    - name: Install dependencies
      run: |
        luarocks install moonscript
        luarocks install busted
        luarocks make

    - name: Run tests
      run: |
        busted

